name: status_saver
description: Status Saver â€“ Story Saver for WhatsApp (multi-WhatsApp, multi-user, APK)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  permission_handler: ^11.3.1
  video_player: ^2.9.2
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
